language: r
warnings_are_errors: true
sudo: false
cache: packages

r:
 - release
 - devel

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change
